# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftTemplet' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftTemplet
#  pod 'AImage'
    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'AlamofireObjectMapper'

#    pod 'Aspects'
#   pod 'Argo'
#
#   pod 'BluetoothKit'

    pod 'CryptoSwift'
#    pod 'EZSwiftExtensions'

#   pod 'Dollar'
#
#   pod 'FoldingCell'
#
#   pod 'Gifu'
#
#   pod 'ImagePicker'
#
#   pod 'KeychainAccess'
    pod 'Kingfisher'
    pod 'SDWebImage'

#   pod 'MonkeyKing'
#   pod 'Moya'
#  
#   pod 'Nimble'
#   pod 'NumberMorphView'
#
#   pod 'ObjectMapper'
#
#   pod 'Permission'
#   pod 'PromiseKit'

#   pod 'Quick'
#
#   pod 'ReachabilitySwift'
#  
#   pod 'SQLite.swift'
   pod 'SnapKit'
#   pod 'Spring'
#   pod 'StarWars'
   pod 'Surge'
#   pod 'SwiftOCR'
#   pod 'SwiftString'
   pod 'SwiftyJSON'
#   pod 'SwiftyUserDefaults'
#
#   pod 'TZStackView'

#   pod 'Whisper'

    pod 'RxAlamofire'
    pod 'RxBlocking'
#    pod 'RxCocoa'
    pod 'RxSwift'
    
#    pod 'ObjectMapper+Realm'
    pod 'HandyJSON'

    pod 'SwiftExpand'

end
